user daemon

pidfile /tmp/sniproxy.pid

error_log {
    syslog daemon
    priority notice
}

listener 0.0.0.0:80 {
    protocol http
    table TableHTTP
    fallback 127.0.0.1:7890
}

listener 0.0.0.0:443 {
    protocol tls
    table TableHTTPS
    fallback 127.0.0.1:7891
}

table TableHTTP {
    example.myftp.org 10.0.0.16:9080
    example.noip.me 127.0.0.1:9080
    example.ddns.net 127.0.0.1:9080
}

table TableHTTPS {
    example.myftp.org 10.0.0.16:2443
    example.noip.me 127.0.0.1:3443
    example.ddns.net 127.0.0.1:4443
}
